### ISSUE TITLE
quantize的scale计算

### ISSUE THREAD

**Issue by shuyuan-wang** [caiwanxianhust/llamabycuda#1]
你好，想请问一下为什么这里的scale是现算出来的，而不是从torch端统计出来当成参数放进去？
![image](https://github.com/user-attachments/assets/ae440806-6144-451d-89fd-7d7c3cc19ad8)

**Comment by caiwanxianhust** [comment]
权重是固定的，所以权重的scale是提前算好的，激活值的scale是推理过程中顺带计算的，根据样本不同，scale值也不是固定的。你说的根据统计值算出一个scale当成固定参数传进去，每个样本都用相同的scale值进行量化，我之前看FasterTransformer也有这么做过，这里没有采用这种方式。

**Comment by caiwanxianhust** [comment]
> 你好，想请问一下为什么这里的scale是现算出来的，而不是从torch端统计出来当成参数放进去？ ![image](https://private-user-images.githubusercontent.com/104115572/394198163-ae440806-6144-451d-89fd-7d7c3cc19ad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjQ2NTQsIm5iZiI6MTczMzgyNDM1NCwicGF0aCI6Ii8xMDQxMTU1NzIvMzk0MTk4MTYzLWFlNDQwODA2LTYxNDQtNDUxZC04OWZkLTdkN2MzY2MxOWFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwOTUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmE2ZmFhNmUyMmM3YmIwNGMxMTkyMjM4Y2RmYTAxMTJjZjBiNzZhNWIzNTg5ZDlmMGY0MTBkMjcxMzUwOTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cdggCOPPWqxnGyRqgdsT2He3EMpOsnxYBJ-xc2_xw_8)

权重是固定的，所以权重的scale是提前算好的，激活值的scale是推理过程中顺带计算的，根据样本不同，scale值也不是固定的。你说的根据统计值算出一个scale当成固定参数传进去，每个样本都用相同的scale值进行量化，我之前看FasterTransformer也有这么做过，这里没有采用这种方式。

**Comment by shuyuan-wang** [comment]
> > 你好，想请问一下为什么这里的scale是现算出来的，而不是从torch端统计出来当成参数放进去？ ![image](https://private-user-images.githubusercontent.com/104115572/394198163-ae440806-6144-451d-89fd-7d7c3cc19ad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjQ2NTQsIm5iZiI6MTczMzgyNDM1NCwicGF0aCI6Ii8xMDQxMTU1NzIvMzk0MTk4MTYzLWFlNDQwODA2LTYxNDQtNDUxZC04OWZkLTdkN2MzY2MxOWFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwOTUyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmE2ZmFhNmUyMmM3YmIwNGMxMTkyMjM4Y2RmYTAxMTJjZjBiNzZhNWIzNTg5ZDlmMGY0MTBkMjcxMzUwOTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cdggCOPPWqxnGyRqgdsT2He3EMpOsnxYBJ-xc2_xw_8)
> 
> 权重是固定的，所以权重的scale是提前算好的，激活值的scale是推理过程中顺带计算的，根据样本不同，scale值也不是固定的。你说的根据统计值算出一个scale当成固定参数传进去，每个样本都用相同的scale值进行量化，我之前看FasterTransformer也有这么做过，这里没有采用这种方式。

好的谢谢，因为之前都是用的英伟达那一套，好像用的都是统计的固定值
